# .github/dependabot.yml
# name = dependabot.yml  # noqa: E265
# description = Automated dependency update configuration via Dependabot
# category = ci  # noqa: E265
# usage = Schedule weekly updates for multiple ecosystems via Dependabot
# behavior = Opens pull requests to update dependencies for pip, Docker, GitHub Actions, npm, and lockfiles
# inputs = Dependabot config fields; no secrets required  # noqa: E265
# outputs = Pull requests with updated dependency versions  # noqa: E265
# dependencies = none  # noqa: E265
# author = Byron Williams  # noqa: E265
# last_modified = 2025-04-17  # noqa: E265
# tags = dependencies, automation  # noqa: E265
# changelog = Initial Dependabot configuration  # noqa: E265
version: 1
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "America/Los_Angeles"
    allow:
      - dependency-type: "direct"
    groups:
      python-patch:
        patterns: ["*"]
        update-types: ["patch", "minor"]
    open-pull-requests-limit: 5
    labels: ["dependencies", "python", "security"]
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-base-images:
        patterns: ["*"]
    labels: ["dependencies", "docker"]
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "github-actions"]
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/tools"
    schedule:
      interval: "weekly"
    groups:
      node-tools:
        patterns: ["*"]
    labels: ["dependencies", "node", "npm"]
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    update-type: "lockfile-only"
    labels: ["dependencies", "lockfile"]
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/src/flask"
    schedule:
      interval: "daily"
    labels: ["dependencies", "docker"]
    commit-message:
      prefix: "chore"
      include: "scope"
