version: 1
updates:

  ################################
  # Python (Poetry - backend / tools)
  ################################
  - package-ecosystem: "pip"
    directory: "/"  # assumes pyproject.toml is at repo root
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "America/Los_Angeles"
    allow:
      - dependency-type: "direct"
    groups:
      python-patch:
        patterns: ["*"]
        update-types: ["patch", "minor"]
    open-pull-requests-limit: 5
    labels: ["dependencies", "python", "security"]
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"

  ################################
  # Docker (e.g., Dockerfile.dev, Dockerfile.production)
  ################################
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-base-images:
        patterns: ["*"]
    labels: ["dependencies", "docker"]
    commit-message:
      prefix: "chore"
      include: "scope"

  ################################
  # GitHub Actions
  ################################
  - package-ecosystem: "github-actions"
    directory: "/"  # workflows live in .github/workflows
    schedule:
      interval: "weekly"
    labels: ["dependencies", "github-actions"]
    commit-message:
      prefix: "chore"
      include: "scope"

  ################################
  # npm / node (for markdownlint-cli, etc.)
  ################################
  - package-ecosystem: "npm"
    directory: "/tools"  # adjust if your package.json is in a subfolder
    schedule:
      interval: "weekly"
    groups:
      node-tools:
        patterns: ["*"]
    labels: ["dependencies", "node", "npm"]
    commit-message:
      prefix: "chore"
      include: "scope"

  ################################
  # Optional: lockfile-only updates (e.g., keep poetry.lock or package-lock.json fresh)
  ################################
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    update-type: "lockfile-only"
    labels: ["dependencies", "lockfile"]
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: docker
    directory: /src/flask
    schedule:
      interval: daily
