version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ledgerbase-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./docker/flask
    container_name: ledgerbase-api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"

volumes:
  pgdata: