# pyproject.toml

# Specifies the build system (optional if you don't build/distribute the package, but good practice)
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# Basic project metadata (optional, but recommended for clarity)
# Fill these out with your actual project details
[project]
name = "ledgerbase" # Or your actual project name
version = "0.1.0"    # Start with an initial version
description = "Description of your LedgerBase project."
requires-python = ">=3.8" # Set your minimum supported Python version
# You can also list dependencies here if you structure your project as an installable package
# dependencies = [
#     "Flask>=2.0",
#     "Flask-SQLAlchemy",
#     "cryptography",
#     "python-dotenv",
#     "sentry-sdk[flask]",
#     "marshmallow",
#     "Flask-Limiter",
#     # Add other runtime dependencies
# ]

# Configuration for the 'black' code formatter
[tool.black]
line-length = 88 # A common line length, often used with flake8 default

# Configuration for the 'isort' import sorter
[tool.isort]
profile = "black" # <--- This is the crucial line for compatibility
# isort will automatically use the line_length defined in [tool.black] if present
