[tool.poetry]
name = "ledgerbase"
version = "0.1.0"
description = "A financial ledger and budgeting application."
authors = ["Byron Williams"]
license = "MIT"
readme = "README.md"
packages = [{ include = "ledgerbase", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
Flask = "3.0.3"
Flask-SQLAlchemy = "3.1.1"
cryptography = "44.0.1"
python-dotenv = "1.0.1"
sentry-sdk = { extras = ["flask"], version = "2.25.1" }
marshmallow = "3.21.2"
Flask-Limiter = "3.5.0"
gunicorn = "^23.0.0"
psycopg = { version = "3.1.18", extras = ["binary"] }
python-dateutil = "2.9.0.post0"
plaid-python = "^15.3.0"
PyYAML = "6.0.1"
jinja2 = "^3.1.6"


[tool.poetry.group.dev.dependencies]
pytest = "8.2.0"
pre-commit = "3.7.0"
black = "24.4.2"
mypy = "^1.9.0"
bandit = "^1.7.8"
types-requests = "^2.31.0.10"
nox = "^2025.2.9"
pathspec = "^0.12.1"
pydantic = "^2.11.3"
sphinx = "^8.2.3"
doc8 = "^1.1.2"
jinja2 = "^3.1.6"
ruff = "^0.11.5"

[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = false

[tool.ruff]
target-version = "py311"
line-length = 88
fix = true
show-fixes = true
extend-ignore = ["E265"]

[tool.ruff.format]
quote-style = "double"
line-ending = "auto"
docstring-code-format = true
indent-style = "space"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D100",  # Missing docstring in public module
  "D104",  # Missing docstring in public package
  "D107",  # Missing docstring in __init__
  "ANN101",  # Missing type annotation for self in method
  "T201",  # print() used
  "D203",  # 1 blank line required before class docstring
  "D213",  #Multi-line docstring summary should start at the second line
  "D205",  # Docstring under triple quotes shouldbe on the same line
]
exclude = [
  ".git",
  ".nox",
  ".venv",
  "build",
  "dist",
  "migrations",
  "__pycache__",
  "tests",
]

[tool.ruff.lint.isort]
known-first-party = ["ledgerbase"]
combine-as-imports = true




#[tool.mypy]
#python_version = "3.12"
#warn_unused_configs = true
#disallow_untyped_defs = true
#disallow_incomplete_defs = true
#no_implicit_optional = true
#check_untyped_defs = true
#ignore_missing_imports = true
#namespace_packages = true
#show_error_codes = true
#strict_equality = true

[tool.mypy.requests]
ignore_missing_imports = true

[tool.mypy."flask.*"]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
