# name = semgrep.yml
# description = Semgrep configuration for detecting misconfigurations and secrets in config files.
# category = dev
# usage = Used during CI to validate configuration files for security misconfigurations and exposed secrets.
# behavior = Scans infrastructure and app config files for unsafe settings or exposed values.
# inputs = YAML/TOML/JSON configuration files
# outputs = terminal scan results, CI logs
# dependencies = Semgrep CLI
# author = Byron Williams
# last_modified = 2025-04-17
# tags = config, security, misconfig
# changelog = Metadata header added; targets config misconfigurations and secrets.

rules:
  - ruleset: r/semgrep-misconfigurations
  - ruleset: r/secrets
