name: Docker Build and Push

on:
    workflow_call:
        inputs:
            docker-image:
                required: true
                type: string
            context:
                required: false
                default: .
                type: string
            dockerfile:
                required: false
                default: Dockerfile
                type: string
            push:
                required: false
                default: true
                type: boolean

permissions:
    contents: read

jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with:
                  egress-policy: audit

            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

            - name: Log in to DockerHub
              uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and optionally push Docker image
              uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
              with:
                  context: ${{ inputs.context }}
                  file: ${{ inputs.dockerfile }}
                  push: ${{ inputs.push }}
                  tags: ${{ inputs.docker-image }}
