name: Docker Build and Push

on:
    workflow_call:
        inputs:
            docker-image:
                required: true
                type: string
            context:
                required: false
                default: .
                type: string
            dockerfile:
                required: false
                default: Dockerfile
                type: string
            push:
                required: false
                default: true
                type: boolean

jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Log in to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build and optionally push Docker image
                uses: docker/build-push-action@v5
                with:
                    context: ${{ inputs.context }}
                    file: ${{ inputs.dockerfile }}
                    push: ${{ inputs.push }}
                    tags: ${{ inputs.docker-image }}
