name: Generate Security Session Matrix

on:
  workflow_call:
    outputs:
      sessions:
        description: "Discovered security-related nox sessions"
        value: ${{ jobs.generate.outputs.sessions }}

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare Poetry & Assured OSS
    uses: ./.github/workflows/templates/prepare-poetry.yml
    with:
      GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
    secrets:
      GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}

  generate:
    name: Discover Sessions
    needs: prepare
    runs-on: ubuntu-latest
    outputs:
      sessions: ${{ steps.set-matrix.outputs.sessions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify no public PyPI fallback
        run: poetry run nox -s verify_assured

      - name: Run session discovery
        id: discover
        run: |
          poetry run nox -s list-security-sessions > matrix.json
          echo "Discovered sessions:"
          cat matrix.json

      - name: Validate and export matrix
        id: set-matrix
        run: |
          if [ ! -s matrix.json ]; then
            echo "::error::No sessions discovered."
            exit 1
          fi
          sessions=$(cat matrix.json)
          echo "sessions=$sessions" >> $GITHUB_OUTPUT
