name: Run Lint Session Matrix

on:
  workflow_call:
    inputs:
      sessions:
        required: true
        type: string

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare Poetry & Assured OSS
    uses: ./.github/workflows/templates/prepare-poetry.yml
    with:
      GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
    secrets:
      GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}

  lint-matrix:
    name: Run ${{ matrix.session }}
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        session: ${{ fromJson(inputs.sessions) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify no public PyPI fallback
        run: poetry run nox -s verify_assured

      - name: Run lint session
        env:
          SESSION: ${{ matrix.session }}
        run: |
          poetry run nox -s "$SESSION"
