name: Nox Task

# This is a reusable template for running a single nox session on a fixed Python version.

on:
  workflow_call:
    inputs:
      sessions:
        required: true
        type: string
      python-version:
        required: false
        type: string
        default: "3.11"

jobs:
  nox-single:
    name: Run nox -s ${{ inputs.session }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4.8.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache Poetry + pip + .nox
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
            .nox
          key: ${{ runner.os }}-nox-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-nox-${{ inputs.python-version }}-

      - name: Install Nox
        run: python -m pip install --upgrade nox

      - name: Run nox -s ${{ inputs.session }}
        run: |
            echo "${{ inputs.sessions }}" | xargs -n1 echo "-s" | xargs nox
