name: Security - Safety

permissions:
    contents: read
    security-events: write
    pull-requests: write

jobs:
    safety:
        name: Run Safety security scan
        runs-on: ubuntu-22.04

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4.1.0

            -   name: Set up Python
                uses: actions/setup-python@v4.8.0
                with:
                    python-version: "3.12"

            -   name: Install Safety
                run: |
                    python -m pip install --upgrade pip
                    pip install safety

            -   name: Run Safety scan
                run: |
                    safety check --full-report --json > safety_output.json

            -   name: Verify output exists
                run: |
                    if [ ! -f safety_output.json ]; then
                      echo "::error::safety_output.json not found!"
                      exit 1
                    fi

            -   name: Count high or critical vulnerabilities
                id: count
                run: |
                    high=$(jq '[.vulnerabilities[] | select(.severity == "high" or .severity == "critical")] | length' safety_output.json)
                    echo "vulns=$high" >> $GITHUB_OUTPUT
                    echo "Found $high high/critical vulnerabilities"

            -   name: Upload Safety report
                uses: actions/upload-artifact@v3
                with:
                    name: safety-report
                    path: safety_output.json

            -   name: Convert to SARIF
                run: |
                    pip install safety-sarif
                    safety-sarif safety_output.json > safety.sarif

            -   name: Upload SARIF to GitHub Security tab
                uses: github/codeql-action/upload-sarif@v3.24.9
                with:
                    sarif_file: safety.sarif

            -   name: Fail on high/critical issues
                if: steps.count.outputs.vulns != '0'
                run: |
                    echo "::error::Safety scan found ${{ steps.count.outputs.vulns }} high/critical issues"
                    exit 1

            -   name: Label PR if issues found
                if: github.event_name == 'pull_request' && steps.count.outputs.vulns != '0'
                uses: actions/github-script@v7.1.0
                with:
                    script: |
                        const pr = context.payload.pull_request;
                        if (!pr) {
                          console.log("No PR context. Skipping label.");
                          return;
                        }
                        await github.rest.issues.addLabels({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: pr.number,
                          labels: ['security:safety']
                        });
