name: Run Security Session Matrix

on:
  workflow_call:
    inputs:
      sessions:
        required: true
        type: string
      python-version:
        required: false
        type: string
        default: "3.11"

jobs:
  security-matrix:
    name: Discover Python versions
    runs-on: ubuntu-22.04
    outputs:
      python-version: ${{ steps.set-matrix.outputs.versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load Python versions from python-versions.json (if default)
        if: inputs.python-version == '3.11'
        id: set-matrix
        run: |
          echo "Loading versions from python-versions.json..."
          versions=$(jq -c .python_versions .github/workflows/templates/python-versions.json)
          echo "versions=$versions" >> $GITHUB_OUTPUT

  run-matrix:
    needs: security-matrix
    if: inputs.python-version == '3.11'
    strategy:
      matrix:
        session: ${{ fromJson(inputs.sessions) }}
        python-version: ${{ fromJson(needs.security-matrix.outputs.python-version) }}
    runs-on: ubuntu-22.04
    name: Run ${{ matrix.session }} [Py ${{ matrix.python-version }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Nox
        run: python -m pip install --upgrade nox

      - name: Run SARIF-compatible Nox session
        run: |
          echo "Running session: ${{ matrix.session }}"
          case "${{ matrix.session }}" in
            bandit)
              nox -s bandit
              cp bandit-report.json bandit.sarif || echo "{}" > bandit.sarif
              ;;
            semgrep)
              nox -s semgrep
              ;;
            pip-audit)
              nox -s pip-audit
              ;;
            trivy)
              nox -s trivy
              ;;
            snyk_scan)
              nox -s snyk_scan || true
              ;;
            safety)
              nox -s safety
              ;;
            sbom)
              nox -s sbom
              ;;
            *)
              nox -s ${{ matrix.session }}
              ;;
          esac

      - name: Upload SARIF files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sarif-${{ matrix.session }}-${{ matrix.python-version }}
          path: |
            *.sarif
          retention-days: 2

  run-override:
    if: inputs.python-version != '3.11'
    strategy:
      matrix:
        session: ${{ fromJson(inputs.sessions) }}
        python-version: ${{ fromJson(inputs.python-version) }}
    runs-on: ubuntu-22.04
    name: Run ${{ matrix.session }} [Py ${{ matrix.python-version }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Nox
        run: python -m pip install --upgrade nox

      - name: Run SARIF-compatible Nox session
        run: |
          echo "Running session: ${{ matrix.session }}"
          case "${{ matrix.session }}" in
            bandit)
              nox -s bandit
              cp bandit-report.json bandit.sarif || echo "{}" > bandit.sarif
              ;;
            semgrep)
              nox -s semgrep
              ;;
            pip-audit)
              nox -s pip-audit
              ;;
            trivy)
              nox -s trivy
              ;;
            snyk_scan)
              nox -s snyk_scan || true
              ;;
            safety)
              nox -s safety
              ;;
            sbom)
              nox -s sbom
              ;;
            *)
              nox -s ${{ matrix.session }}
              ;;
          esac

      - name: Upload SARIF files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sarif-${{ matrix.session }}-${{ matrix.python-version }}
          path: |
            *.sarif
          retention-days: 2
