<!-- SPDX-FileCopyrightText: © 2019–2025 Byron Williams -->
<!-- SPDX-License-Identifier: MIT -->

> **NOTE:** This file is maintained centrally in the organization’s `.github` repository.
> For the latest version, see:
> https://github.com/williaby/.github/blob/main/.github/ISSUE_TEMPLATE/bug.yml
