name: Security - Trivy

on:
    pull_request:
        branches: [ main ]
    push:
        branches: [ main ]

permissions:
    contents: read
    security-events: write
    pull-requests: write

jobs:
    trivy:
        name: Run Trivy vulnerability scan
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4.1.0

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2.9.1

            -   name: Build Docker image
                run: docker build -t ledgerbase:latest .

            -   name: Run Trivy with SARIF output
                uses: aquasecurity/trivy-action@v0.11.2
                with:
                    image-ref: 'ledgerbase:latest'
                    format: 'sarif'
                    output: 'trivy-results.sarif'
                    exit-code: '0'               # Allow scan to proceed
                    ignore-unfixed: true
                    severity: 'HIGH,CRITICAL'

            -   name: Check if SARIF file was created
                run: |
                    if [ ! -f trivy-results.sarif ]; then
                      echo "::error::SARIF output not found. Trivy scan may have failed."
                      exit 1
                    fi

            -   name: Count HIGH/CRITICAL issues in SARIF
                id: count
                run: |
                    count=$(jq '[.runs[].results[] | select(.level == "error" or .level == "warning")] | length' trivy-results.sarif)
                    echo "Total HIGH/CRITICAL issues: $count"
                    echo "vulns=$count" >> $GITHUB_OUTPUT

            -   name: Upload SARIF to GitHub Security tab
                uses: github/codeql-action/upload-sarif@v3.24.9
                with:
                    sarif_file: trivy-results.sarif

            -   name: Fail job if high-severity vulnerabilities found
                if: steps.count.outputs.vulns != '0'
                run: |
                    echo "::error::Trivy found ${{ steps.count.outputs.vulns }} HIGH or CRITICAL vulnerabilities."
                    exit 1

            -   name: Label PR if Trivy issues found
                if: github.event_name == 'pull_request' && steps.count.outputs.vulns != '0'
                uses: actions/github-script@v7.1.0
                with:
                    script: |
                        const label = 'security:trivy';
                        const pr = context.payload.pull_request;
                        if (!pr) {
                          console.log("No pull request context. Skipping label.");
                          return;
                        }
                        await github.rest.issues.addLabels({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: pr.number,
                          labels: [label],
                        });
