name: Security - pip-audit

on:
    pull_request:
        branches: [ main ]
    push:
        branches: [ main ]
    workflow_dispatch:

permissions:
    contents: read
    security-events: write
    pull-requests: write

jobs:
    pip-audit:
        name: Run pip-audit security scan
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4.1.0

            -   name: Set up Python
                uses: actions/setup-python@v4.8.0
                with:
                    python-version: "3.12"

            -   name: Install pip-audit
                run: |
                    python -m pip install --upgrade pip
                    pip install pip-audit

            -   name: Run pip-audit
                run: |
                    pip-audit --output pip-audit-results.json --format json

            -   name: Verify pip-audit results file exists
                run: |
                    if [ ! -f pip-audit-results.json ]; then
                      echo "::error::pip-audit-results.json not found!"
                      exit 1
                    fi

            -   name: Count high-severity issues
                id: count
                run: |
                    high=$(jq '[.[] | select(.vulns[]?.severity == "high" or .vulns[]?.severity == "critical")] | length' pip-audit-results.json)
                    echo "High/critical issues: $high"
                    echo "vulns=$high" >> $GITHUB_OUTPUT

            -   name: Upload audit results
                uses: actions/upload-artifact@v3
                with:
                    name: pip-audit-results
                    path: pip-audit-results.json

            -   name: Convert to SARIF
                run: |
                    pip install pip-audit-sarif
                    pip-audit-sarif --input pip-audit-results.json --output pip-audit-results.sarif

            -   name: Upload SARIF to GitHub Security tab
                uses: github/codeql-action/upload-sarif@v3.24.9
                with:
                    sarif_file: pip-audit-results.sarif

            -   name: Fail if high-severity issues found
                if: steps.count.outputs.vulns != '0'
                run: |
                    echo "::error::pip-audit found ${{ steps.count.outputs.vulns }} high or critical vulnerabilities"
                    exit 1

            -   name: Label PR on issues
                if: github.event_name == 'pull_request' && steps.count.outputs.vulns != '0'
                uses: actions/github-script@v7.1.0
                with:
                    script: |
                        const pr = context.payload.pull_request;
                        if (!pr) {
                          console.log("No PR context. Skipping label.");
                          return;
                        }
                        await github.rest.issues.addLabels({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: pr.number,
                          labels: ['security:pip-audit']
                        });
