name: Auto-Merge PRs

on:
    pull_request:
        types: [ labeled ]

permissions:
    pull-requests: write
    contents: read

jobs:
    auto-merge:
        if: ${{ github.event.label.name == 'status:auto-approved' && (github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]') }}
        runs-on: ubuntu-latest

        steps:
            -   name: Enable auto-merge
                uses: actions/github-script@v7
                with:
                    script: |
                        try {
                          const pr = context.payload.pull_request;
                          if (!pr) {
                            throw new Error("No pull request found in the payload.");
                          }

                          console.log(`Merging PR #${pr.number} from ${pr.user.login}`);
                          await github.rest.pulls.merge({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            pull_number: pr.number,
                            merge_method: "squash"
                          });
                        } catch (error) {
                          core.setFailed(`❌ Failed to merge PR: ${error.message}`);
                        }
