name: Pre-Commit

on:
    push:
        branches: [ main ]
    pull_request:
    workflow_dispatch:

jobs:
    pre-commit:
        uses: ./.github/workflows/templates/nox-template.yml
        with:
            sessions: "precommit"
