name: Auto-Merge Trusted PR

on:
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: |
      github.event.label.name == 'status:auto-approved' &&
      (github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]')
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: "squash"
            });
