---
# Front-Matter for GitHub Workflow

title: "CIFuzz Workflow"
name: "cifuzz.yml"
description: "Fuzz testing workflow leveraging CIFuzz (OSS-Fuzz) to detect hard-to-find bugs in LedgerBase"
category: ci
usage: "Trigger on push to main/develop, pull_request, or manual dispatch"
behavior: "Sets up environment; builds fuzzers; runs fuzzing; uploads crash artifacts; generates SARIF"
inputs: "triggers: push(main,develop), pull_request(main,develop), workflow_dispatch; secrets: none"
outputs: "Crash artifacts under out/artifacts; SARIF report under sarif/cifuzz.sarif"
dependencies: "step-security/harden-runner@v2.12.0, actions/checkout@v4, google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master, google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master, actions/upload-artifact@v3, github/codeql-action/upload-sarif@v2"
author: "Byron Williams"
last_modified: "2025-04-17"
changelog: "Bumped harden-runner, checkout, artifact & SARIF upload actions to latest majors"
tags: [ci, fuzzing, security]
---

name: CIFuzz Workflow

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write

jobs:
  fuzz:
    name: Build & Run Fuzzers
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Harden runner (audit outbound)
        uses: step-security/harden-runner@v2.12
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Fuzzers
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
        with:
          oss-fuzz-project-name: "ledgerbase"

      - name: Run Fuzzers
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
        with:
          oss-fuzz-project-name: "ledgerbase"
          fuzz-seconds: 600
          output-sarif: true

      - name: Upload crash artifacts
        if: failure() && steps.build.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: cifuzz-artifacts
          path: out/artifacts

      - name: Upload CIFuzz SARIF
        if: always() && steps.build.outcome == 'success'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif/cifuzz.sarif
