---
# Front-Matter for GitHub Workflow

title: "Dependency Review Workflow"
name: "dependency-review.yml"
description: "Scans dependency changes in pull requests and blocks known-vulnerable versions"
category: ci
usage: "Trigger on pull_request to review dependencies via GitHub Dependency Review Action"
behavior: "Flags vulnerable dependencies in PRs; blocks merge if required"
inputs: "GitHub pull_request event payload; no secrets"
outputs: "GitHub check results for dependency safety"
dependencies: "step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf, actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683, actions/dependency-review-action@67d4f4bd7a9b17a0db54d2a7519187c65e339de8"
author: "Byron Williams"
last_modified: "2023-11-15"
changelog: "Pinned all action SHAs; added annotation header; converted to YAML front-matter format"
tags: [security, dependencies]
---

name: "Dependency Review"

on:
    pull_request:
    workflow_dispatch: {}

permissions:
    contents: read

jobs:
    dependency-review:
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@v2.12
              with:
                  egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Dependency Review
              uses: actions/dependency-review-action@v4
