name: Deploy to Unraid

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  deploy:
    name: Build, Backup, Deploy LedgerBase
    runs-on: [self-hosted, ledgerbase, deployment]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u williaby --password-stdin

      - name: Tag and build image
        run: |
          VERSION=${GITHUB_REF##*/}
          docker build -t ghcr.io/williaby/ledgerbase:latest -t ghcr.io/williaby/ledgerbase:$VERSION .

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/williaby/ledgerbase:latest
          docker push ghcr.io/williaby/ledgerbase:${GITHUB_REF##*/}

      - name: Backup running volumes (named or bind-mounted)
        run: |
          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          docker run --rm \
            -v ledgerbase_data:/data \
            -v $PWD:/backup \
            alpine \
            tar czf /backup/ledgerbase-data-$TIMESTAMP.tar.gz -C /data .

      - name: Backup current image
        run: |
          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          docker save ghcr.io/williaby/ledgerbase:latest | gzip > ledgerbase-image-$TIMESTAMP.tar.gz

      - name: Pull and deploy with Docker Compose
        run: |
          docker compose pull
          docker compose up -d --remove-orphans
