name: Dev Checks

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:
      inputs:
        session:
          description: "Nox session to run (one at a time)"
          required: true
          default: "lint typecheck gen_script_docs"


jobs:
    matrix:
        name: Load Python Version Matrix
        runs-on: ubuntu-latest
        outputs:
            versions: ${{ steps.load.outputs.versions }}
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with:
                egress-policy: audit

            -   name: Checkout
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            -   name: Install yq
                run: |
                    sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
                    sudo chmod +x /usr/bin/yq

            -   name: Extract Python version array
                id: load
                run: |
                    versions=$(yq e '.python-versions' .github/workflows/templates/python-version-matrix.yml -o=json)
                    echo "versions=$versions" >> "$GITHUB_OUTPUT"

    dev-checks:
        name: Nox Dev Checks
        needs: matrix
        strategy:
            matrix:
                python-version: ${{ fromJson(needs.matrix.outputs.versions) }}

        uses: ./.github/workflows/templates/nox-template.yml
        with:
          python-version: ${{ matrix.python-version }}
          sessions: ${{ inputs.session }}
