name: Dev Checks

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint-test:
        name: Lint, Type Check, Format
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.12'

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install \
                      black \
                      isort \
                      flake8 \
                      mypy \
                      bandit \
                      types-requests

            -   name: Run Black
                run: black --check --config setup.cfg .

            -   name: Run isort
                run: isort --check-only --settings-path setup.cfg .

            -   name: Run flake8
                run: flake8 --config=setup.cfg .

            -   name: Run mypy
                run: mypy --config-file setup.cfg .

            -   name: Run Bandit (security linter)
                run: bandit -r . -x tests --skip B101
