name: Dev Checks

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint-test:
        name: Lint, Type Check, Format
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.12'

            -   name: Install Poetry
                run: |
                    curl -sSL https://install.python-poetry.org | python3 -
                    echo "$HOME/.local/bin" >> $GITHUB_PATH

            -   name: Install dependencies
                run: |
                    poetry install --no-interaction --no-root

            -   name: Run Black
                run: poetry run black --check .

            -   name: Run isort
                run: poetry run isort --check-only .

            -   name: Run flake8
                run: poetry run flake8 .

            -   name: Run mypy
                run: poetry run mypy .

            -   name: Run Bandit (security linter)
                run: poetry run bandit -r src/ledgerbase -x tests --skip B101
