name: Generate Security Session Matrix

on:
  workflow_call:
    outputs:
      sessions:
        description: "Discovered security-related nox sessions"
        value: ${{ jobs.generate.outputs.sessions }}

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-22.04
    outputs:
      sessions: ${{ steps.set-matrix.outputs.sessions }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.11'

      - name: Install Nox
        run: python -m pip install --upgrade nox

      - name: Run session discovery
        run: |
          set -e
          python -m nox -s list-security-sessions > matrix.json
          echo "Discovered sessions:"
          cat matrix.json

      - name: Validate and export matrix
        id: set-matrix
        run: |
          if [ ! -s matrix.json ]; then
            echo "::error::No sessions discovered."
            exit 1
          fi
          sessions=$(cat matrix.json)
          echo "sessions=$sessions" >> $GITHUB_OUTPUT
