# name = gh-pages.yml
# description = GitHub workflow that builds and deploys project documentation to GitHub Pages
# category = maintainability
# usage = Automatically triggered when code is pushed to the main branch
# behavior = Builds Sphinx HTML documentation and deploys it to the gh-pages branch
# inputs = Project source code and documentation files
# outputs = HTML documentation published to GitHub Pages
# dependencies = Sphinx, peaceiris/actions-gh-pages action
# author = LedgerBase Team
# last_modified = 2023-11-15
# changelog = Initial version

name: 📚 Build & Deploy Docs

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx HTML
        run: |
          sphinx-build -b html docs/source docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages
          user_name: "LedgerBase Bot"
          user_email: "ci@ledgerbase.example.com"
