---
# Front-Matter for GitHub Workflow
title: "Pre-Commit Workflow"
name: "pre-commit.yml"
description: >
  Runs pre-commit hooks via Nox session to enforce code standards
category: workflow
usage: "Trigger on push/PR to main and develop, or manual dispatch, weekly"
behavior: "Executes Nox session \"pre-commit\"; blocks merges if hooks fail"
inputs: "triggers: push(main,develop), pull_request(main,develop), workflow_dispatch, schedule; no secrets"
outputs: "Pre-commit check results"
dependencies: "./.github/workflows/templates/nox-template.yml"
author: "Byron Williams"
last_modified: "2025-04-17"
changelog: "Extended triggers to develop; added schedule; pinned metadata header"
tags: [workflow, ci, lint, pre-commit]
---

name: Pre-Commit

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]
    workflow_dispatch: {}
    schedule:
        - cron: "0 2 * * 0" # Weekly on Sunday at 02:00 UTC

jobs:
    pre-commit:
        uses: ./.github/workflows/templates/nox-template.yml
        with:
            sessions: "pre-commit"
