name: Pre-Commit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
    pre-commit:
        uses: ./.github/workflows/templates/nox-template.yml
        with:
            sessions: "pre-commit"
