# .github/workflows/templates/prepare-poetry.yml
name: Prepare Poetry Environment

on:
    workflow_call:

jobs:
    setup:
        runs-on: ubuntu-latest
        outputs:
            python-version: ${{ steps.setup-python.outputs.python-version }}

        steps:
            -   name: Set up Python
                id: setup-python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.12'

            -   name: Cache Poetry Dependencies
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.cache/pypoetry
                        ~/.virtualenvs
                    key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-poetry-

            -   name: Install Poetry
                uses: snyk/actions/install-poetry@v3
                with:
                    version: latest

            -   name: Install Dependencies
                run: poetry install --no-interaction

            -   name: Export Dev Requirements
                run: |
                    poetry export --only dev --without-hashes --format=requirements.txt > dev-requirements.txt
