name: Python (pip) Task

on:
    workflow_call:
        inputs:
            python-version:
                required: true
                type: string
                description: Python version to set up
            run-command:
                required: true
                type: string
                description: Command to execute

jobs:
    run:
        name: Python (pip) Task
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: ${{ inputs.python-version }}

            -   name: Upgrade pip and install requirements
                run: |
                    python -m pip install --upgrade pip
                    if [ -f requirements.txt ]; then
                      echo "Installing dependencies from requirements.txt..."
                      pip install -r requirements.txt
                    else
                      echo "⚠️ No requirements.txt found. Skipping dependency installation."
                    fi

            -   name: Run Provided Command
                run: |
                    echo "Running command: ${{ inputs.run-command }}"
                    ${{ inputs.run-command }}
