name: Python (pip) Task

on:
    workflow_call:
        inputs:
            python-version:
                required: true
                type: string
                description: Python version to set up
            run-command:
                required: true
                type: string
                description: Command to execute

permissions:
  contents: read

jobs:
    run:
        name: Python (pip) Task
        runs-on: ubuntu-latest

        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                egress-policy: audit

            -   name: Checkout code
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            -   name: Set up Python
                uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
                with:
                    python-version: ${{ inputs.python-version }}

            -   name: Upgrade pip and install requirements
                run: |
                    python -m pip install --upgrade pip
                    if [ -f requirements.txt ]; then
                      echo "Installing dependencies from requirements.txt..."
                      pip install -r requirements.txt
                    else
                      echo "⚠️ No requirements.txt found. Skipping dependency installation."
                    fi

            -   name: Run Provided Command
                run: |
                    echo "Running command: ${{ inputs.run-command }}"
                    ${{ inputs.run-command }}
