name: SBOM (CycloneDX)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM UTC

permissions:
    contents: read
    security-events: write     # for SARIF upload to Security tab
    actions: read

jobs:
    sbom:
        uses: .github/workflows/templates/nox-template-matrix.yml
        with:
            session: "sbom"

    upload-sarif:
        name: Upload SARIF to GitHub Security tab
        needs: sbom
        runs-on: ubuntu-latest
        if: always()

        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                egress-policy: audit

            -   name: Checkout code
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            -   name: Download SARIF from runner
                run: |
                    if [ ! -f sbom.sarif ]; then echo "Missing SARIF file"; exit 1; fi

            -   name: Upload SARIF to GitHub Security tab
                uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47 # v3.28.15
                with:
                    sarif_file: sbom.sarif

    upload-json:
        name: Archive CycloneDX JSON
        needs: sbom
        runs-on: ubuntu-latest
        if: always()

        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                egress-policy: audit

            -   name: Checkout code
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            -   name: Upload CycloneDX JSON artifact
                uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
                with:
                    name: sbom-cyclonedx-json
                    path: sbom.json
