# .github/workflows/sbom.yml
name: Security – SBOM

on:
  push:
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write

jobs:
  sbom:
    name: Generate & Validate SBOM
    runs-on: ubuntu-22.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Trivy & wget
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Install Nox
        run: python -m pip install --upgrade pip nox

      - name: Run SBOM Validate via Nox
        run: nox -s sbom_validate

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom-cyclonedx
          path: docs/generated/sbom/sbom.cdx.json
          retention-days: 7
