name: Security - SBOM

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'  # Run daily at 3 AM UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2.11.1
        with:
          egress-policy: audit

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget -qO trivy.tar.gz https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.52.1_Linux-64bit.tar.gz
          tar -xf trivy.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Build Docker image for SBOM generation
        run: docker build -t ledgerbase:${{ github.sha }} .

      - name: Generate SBOM (CycloneDX format)
        run: |
          trivy image ledgerbase:${{ github.sha }} \
            --format cyclonedx \
            --output sbom.cdx.json

      - name: Validate CycloneDX SBOM
        run: |
          wget -q https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.24.0/cyclonedx-linux-x64 -O cyclonedx
          chmod +x cyclonedx
          ./cyclonedx validate --input-file sbom.cdx.json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: sbom.cdx.json
