---
# Front-Matter for GitHub Workflow
title: "OpenSSF Scorecard Security Scan"
name: "scorecard.yml"
description: "Runs OpenSSF Scorecard to analyze security practices and generate SARIF reports"
category: security
usage: "Triggered weekly, on branch protection rule changes, or on push to main"
behavior: "Analyzes repository security practices and uploads results to GitHub"
inputs: "Repository code"
outputs: "SARIF security analysis results"
dependencies: "ossf/scorecard-action, github/codeql-action"
author: "Byron Williams"
last_modified: "2023-11-15"
changelog: "Updated with front-matter according to annotation spec"
tags: [security, scorecard, ossf]
---

name: Security - Scorecard

on:
    branch_protection_rule:
    schedule:
        - cron: "21 21 * * 2" # Weekly on Tuesdays
    push:
        branches: [main]

permissions: read-all

jobs:
    analysis:
        name: Run Scorecard analysis
        runs-on: ubuntu-latest
        if: github.event.repository.default_branch == github.ref_name || github.event_name == 'pull_request'
        permissions:
            security-events: write
            id-token: write

        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@v2.12
              with:
                  egress-policy: audit

            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Run Scorecard scan
              uses: ossf/scorecard-action@v2
              with:
                  results_file: results.sarif
                  results_format: sarif
                  publish_results: true
                  # Optional: uncomment below to enable branch-protection check on public repos
                  # repo_token: ${{ secrets.SCORECARD_TOKEN }}

            - name: Upload artifact (SARIF JSON)
              uses: actions/upload-artifact@v4
              with:
                  name: scorecard-sarif
                  path: results.sarif
                  retention-days: 5

            - name: Upload to GitHub Code Scanning dashboard
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: results.sarif
