name: Full Repo Secret Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'  # Weekly on Monday @ 3am UTC

jobs:
  trufflehog-full:
    name: TruffleHog Full Repo Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog on full repo
        run: |
          trufflehog git filesystem \
            --fail \
            --regex \
            --entropy \
            --only-verified \
            --branch main \
            --path .
