# name = security-semgrep.yml
# description = Run Semgrep security scans via Nox session using unified .semgrep.yml
# category = security
# usage = Trigger on push to src/**, tests/**, .semgrep.yml; on pull_request; and weekly on Sunday at 02:00 UTC
# behavior = Executes Nox session "semgrep" (which installs Semgrep==1.119.0 and runs .semgrep.yml, producing a SARIF); fails on any findings
# inputs = triggers: schedule, push, pull_request; secrets: none
# outputs = semgrep.sarif
# dependencies = step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf, actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683, actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55, actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f, pip, nox, github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47
# author = Byron Williams
# last_modified = 2025-04-19
# tags = security, semgrep, ci
# changelog = Added pip cache; generate & upload SARIF via Nox session

name: Security – Semgrep via Nox

on:
  schedule:
    - cron: '0 2 * * 0'     # Sunday 02:00 UTC
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.semgrep.yml'
  pull_request:

permissions:
  contents: read

env:
  SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
  SEMGREP_DEPLOYMENT_ID: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}

jobs:
  semgrep:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@...

      - name: Checkout code
        uses: actions/checkout@...

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock','requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Cache Nox venvs
        uses: actions/cache@v3
        with:
          path: .nox
          key: ${{ runner.os }}-nox-${{ hashFiles('noxfile.py') }}
          restore-keys: ${{ runner.os }}-nox-

      - name: Setup Python
        uses: actions/setup-python@...
        with:
          python-version: '3.11'

      - name: Install Nox
        run: python -m pip install --upgrade pip && pip install nox

      - name: Run Semgrep
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            nox -s semgrep-ci
          else
            nox -s semgrep-full
          fi

      - name: Upload SARIF (CI only)
        if: github.event_name == 'pull_request'
        uses: github/codeql-action/upload-sarif@...
        with:
          sarif_file: semgrep-ci.sarif
