name: security-audit

on:
    schedule:
        -   cron: '0 3 * * 0'  # Weekly on Sunday
    workflow_dispatch:

jobs:
    safety-check:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Install Poetry
                run: curl -sSL https://install.python-poetry.org | python3 -

            -   name: Install Safety
                run: poetry add --group dev safety

            -   name: Export dependencies
                run: poetry export --without-hashes --format=requirements.txt > requirements.txt

            -   name: Run Safety audit
                run: poetry run safety check --file=requirements.txt --full-report
