# .github/workflows/security-secrets.yml
name: Secret Scanner

on: [push, pull_request]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan for Secrets
        uses: trufflesecurity/trufflehog@v3.66.3
        with:
          scanArguments: "--regex --entropy --json ."
