# .github/workflows/security-trivy.yml
name: Trivy Docker Image Scan

on:
  push:
    branches: [main]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ledgerbase:latest'
          format: 'table'
          exit-code: '0'
