name: PR Status Summary

on:
    pull_request:
        types: [ opened, synchronize, reopened, labeled, unlabeled ]

jobs:
    summarize:
        name: Summarize Workflow Results
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
            checks: read

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Generate PR summary with coverage
                uses: actions/github-script@v7
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    script: ''                   # Adding an empty script to satisfy the parameter
                    script-file: .github/scripts/pr-status-summary.js
